config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :stores
  get 'users/:id' => 'users#show'
  get 'stores/:id' => 'stores#show'
  root "activities#index"
  resources :activities do
    collection do
      get :activity_area_id
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :activity_images
  belongs_to :store
  belongs_to :prefectural
  belongs_to :area
  accepts_nested_attributes_for :activity_images
end

app/models/activity_image.rb
class ActivityImage < ActiveRecord::Base
  belongs_to :activity
  mount_uploader :image, ImageUploader
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :activities
  belongs_to :prefectural
end

app/models/prefectural.rb
class Prefectural < ActiveRecord::Base
  has_many :activities
  has_many :areas
end

app/models/store.rb
class Store < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
    @activity.activity_images.build
  end

  def activity_area_id
    if request.xhr?
      render partial: 'areas', locals: {prefectural_id: params[:prefectural_id]}
    end
  end

  def create
    Activity.create(activity_params)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def activity_params
    params.require(:activity).permit(:title,:description,:price,:prefectural_id,:area_id,:age,:period,:reservation,:street,activity_images_attributes: [:image]).merge(store_id: current_store.id)
  end

  def activityimage_params
    params.require(:activity_image).permit(:image)
  end
end

app/controllers/activity_images_controller.rb
class ActivityImagesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :configure_permitted_parameters, if: :devise_controller?
  #
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  # end

  layout :layout_by_resource

  protected

    def devise_parameter_sanitizer
      if resource_class == User
        Sanitizer::User::ParameterSanitizer.new(User, :user, params)
      elsif resource_class == Store
        Sanitizer::Store::ParameterSanitizer.new(Store, :store, params)
      else
        super # Use the default one
      end
    end

  def layout_by_resource
    if devise_controller? && resource_name == :store
      "store"
    else
      "application"
    end
  end

end

app/controllers/stores/passwords_controller.rb
class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/sessions_controller.rb
class Stores::SessionsController < Devise::SessionsController
  layout 'store'
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/stores/unlocks_controller.rb
class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def show
    @store = Store.find(current_store.id)
    @activities = Activity.where(store_id: current_store.id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/activity_images_helper.rb
module ActivityImagesHelper
end

app/helpers/activitys_helper.rb
module ActivitysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_areas.html.erb
<%= collection_select :activity, :area_id, Area.where(prefectural_id: prefectural_id), :id, :city %>

app/views/activities/_form.html.erb
<h2>アクティビティ新規作成</h2>

<style>
.form_test ul li{
  margin-bottom: 20px;
}
</style>

<div class="form_test">
<%= form_for @activity do |f| %>
  <ul>
    <li><%= f.text_field :title, placeholder: "タイトル" %></li>
    <li><%= f.text_area :description, placeholder: "説明文"  %></li>
    <li><%= f.text_area :age, placeholder: "対象年齢"  %></li>
    <li><%= f.text_area :period, placeholder: "開催期間"  %></li>
    <li><%= f.text_area :reservation, placeholder: "予約"  %></li>
    <li><%= f.number_field :price, placeholder: "料金" %></li>
    <li><%= f.collection_select :prefectural_id, Prefectural.all, :id, :name %></li>
    <%= render partial: 'areas', locals: {prefectural_id: Prefectural.first.id} %>

    <li><%= f.text_field :street, placeholder: "町名番地" %></li>
      <%= f.fields_for :activity_images do |image| %>
        <li><%= image.file_field :image %></li>
      <% end %>
  </ul>
  <%= f.submit '登録' %>
<% end %>
</div><!-- .form_test -->

app/views/activities/_map.html.erb
<dl>
<dt><a href="javascript:void(0);"><i class="fa fa-map-marker" aria-hidden="true"></i>
アクセス・地図</a></dt>
<dd>

<h3>アクセス方法</h3>
<span class="st">住所</span><p>茨城県常陸太田市天下野町2133-6</p>
<span class="st">お車でお越しの方</span>
<p>関越自動車道「水上IC」より国道291号線経由で約10分

【駐車場について】※約50台分の無料の駐車スペースあり
橋を渡りきったら左折し、すぐ右手にある「みなかみの森」駐車場をご利用ください。
そこから徒歩3分です。大型バスの駐車も可能です。</p>
<h3>MAP</h3>
<div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6392.818297188053!2d138.974022!3d36.760751!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzbCsDQ1JzM5LjIiTiAxMzjCsDU4JzI3LjYiRQ!5e0!3m2!1sja!2sus!4v1475059512804" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe></div>

</dd>
</dl>

app/views/activities/_photo.html.erb
<dl>
<dt><a href="javascript:void(0);"><i class="fa fa-picture-o" aria-hidden="true"></i>
フォト＆動画</a></dt>
<dd>
<h3>フォトギャラリー＆動画</h3>
<p>
<div class="clearfix mosaicflow">
<div class="mosaicflow__item">
<a href="images/posttest1.jpg" data-lightbox="lightbox" title="赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。"><img src="images/posttest1.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest2.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest2.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest3.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest3.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest4.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest4.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest9.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest9.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest5.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest5.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest6.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest6.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest9.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest9.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest7.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest7.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>
<div class="mosaicflow__item">
<a href="images/posttest8.jpg" data-lightbox="lightbox" data-title=""><img src="images/posttest8.jpg" alt=""  />
<p>赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。赤です。</p></a>
</div>

</div>





</p>
</p>
</dd>
</dl>

app/views/activities/_plandetail.html.erb
<dl>
<dt><a href="javascript:void(0);"><i class="fa fa-clone" aria-hidden="true"></i>
プラン詳細</a></dt>
<dd>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
</dd>
</dl>

app/views/activities/_plantop.html.erb
<div class="tabAccordion">
<dl>
<dt><a href="javascript:void(0);"><i class="fa fa-flag" aria-hidden="true"></i>
プラントップ</a></dt>
<dd>

<ul class="slider lazy-item">
  <li class="trim"><a href="#"><img src="images/posttest1.jpg" alt=""  /></a></li>
  <li class="trim"><a href="#"><img src="images/posttest2.jpg" alt=""  /></a></li>
  <li class="trim"><a href="#"><img src="images/posttest3.jpg" alt=""  /></a></li>
  <li class="trim"><a href="#"><img src="images/posttest4.jpg" alt=""  /></a></li>
  <li class="trim"><a href="#"><img src="images/posttest5.jpg" alt=""  /></a></li>
</ul>
 
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
<h3>プラン詳細</h3>
<p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
</dd>
</dl>

app/views/activities/_review.html.erb
<dl>
<dt><a href="javascript:void(0);"><i class="fa fa-comments" aria-hidden="true"></i>
口コミ(8)</a></dt>
<dd>
<h3>口コミ</h3>
<p>現在口コミはありません。<br>
口コミを書いてみませんか？</p>
</p>
</dd>
</dl>

app/views/activities/_sns.html.erb
<div class="sns">
<div id="boxArea" style="display:table;padding:0 0 0 2px;"><div style="width:124px;height:22px;float:left;"><iframe src="//www.facebook.com/v2.0/plugins/like.php?href=http%3A%2F%2Ftest.g-hill.jp%2F07%2F&amp;width&amp;layout=button&amp;action=like&amp;show_faces=false&amp;share=true&amp;height=90&amp;appId=" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:90px;" allowTransparency="true"></iframe></div><div style="width:74px;height:22px;float:left;"><a href="https://twitter.com/share" class="twitter-share-button"{count} data-lang="ja" data-dnt="true">ツイート</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div><div style="width:36px;height:22px;float:left;"><div class="g-plusone" data-size="medium" data-annotation="none"></div>
<script type="text/javascript">
  window.___gcfg = {lang: 'ja'};
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();</script></div><div style="width:82px;height:22px;float:left;"><a href="http://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-layout="standard-noballoon" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script></div><div style="width:67px;height:22px;float:left;"><a data-pocket-label="pocket" data-pocket-count="none" class="pocket-btn" data-lang="en"></a></div><div style="width:86px;height:22px;float:left;"><span><script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411" ></script><script type="text/javascript">new media_line_me.LineButton({"pc":true,"lang":"ja","type":"a"});</script></span></div><div style="width:66px;height:22px;float:left;"><script src="//platform.linkedin.com/in.js" type="text/javascript">lang: ja_JP</script><script type="IN/Share"></script></div></div><script type="text/javascript">!function(d,i){if(!d.getElementById(i)){var j=d.createElement("script");j.id=i;j.src="https://widgets.getpocket.com/v1/j/btn.js?v=1";var w=d.getElementById(i);d.body.appendChild(j);}}(document,"pocket-btn-js");</script>
</div>

app/views/activities/create.html.erb
<p>アクティビティ新規登録完了</p>

<%= link_to '一覧へ戻る', activities_path %>
<%= link_to '続けて追加', new_activity_path %>

app/views/activities/index.html.erb
<div class="post hover01">
<h2><i class="fa fa-star" aria-hidden="true"></i>新着のレジャー・遊び・レッスン・学習</h2>


<%= link_to '一覧', activities_path %>
<%= link_to '新規作成', new_activity_path %>

<% @activities.each do |activity| %>
<h3><%= activity.title %></h3>
<p><%= activity.description %></p>
<p><%= activity.price %>円</p>
<%= link_to '詳細を見る', activity_path(activity) %>
<hr>
<% end %>


<% if store_signed_in? %>
<p><%= link_to "#{current_store.store_name}", "/stores/#{current_store.id}" %>でログイン中</p>
<p><%= link_to "店舗ログアウト", destroy_store_session_path, method: :delete %></p>
<% else %>
<p><%= link_to "店舗ログイン", new_store_session_path %></p>
<p><%= link_to "店舗新規登録", new_store_registration_path %></p>
<% end %>

</div>

app/views/activities/new.html.erb
<%= render 'form' %>

app/views/activities/show.html.erb
<div class="listin">
<h2><%= @activity.title %><span class="okiniiri"><i class="fa fa-heart"></i>お気に入りに追加する</span></h2>
<%= render 'sns' %>
<%= render 'plantop' %>
<%= render 'plandetail' %>
<%= render 'map' %>
<%= render 'photo' %>
<%= render 'review' %>

<script>
$(function(){
    var rwdTab = $('.tabAccordion'),
    switchPoint = 640,
    fadeSpeed = 150,
    slideSpeed = 150;
 
    var btnElm = rwdTab.children('dl').children('dt'),
    contentsArea = rwdTab.children('dl').children('dd');
 
    btnElm.on('click', function(){
        if(!$(this).hasClass('btnAcv')){
            btnElm.removeClass('btnAcv');
            $(this).addClass('btnAcv');
 
            if(window.innerWidth > switchPoint){
                contentsArea.fadeOut(fadeSpeed);
                $(this).next().fadeIn(fadeSpeed);
            } else {
                contentsArea.slideUp(slideSpeed);
                $(this).next().slideDown(slideSpeed);
            }
        }
    });
 
    btnElm.first().click();
});
</script>

<!-- /右予約のとこ -->
<div class="reservation">
<table>
<tbody>
<tr>
<th>料金（税込）</th>
<td><span class="listinprice">¥<%= @activity.price %></span></td>
</tr>
<tr>
<th>対象年齢</th>
<td><%= @activity.age %></td>
</tr>
<tr>
<th>開催期間</th>
<td><%= @activity.period %></td>
</tr>
<tr>
<th>予約</th>
<td><%= @activity.reservation %></td>
</tr>
</tbody>
</table>

<div class="reservationbtn"><a href=""><i class="fa fa-chevron-right" aria-hidden="true"></i>
予約・空き確認する</a></div>

<div class="listincalendar">
<div class="month">10月</div>
<ul>
<li>7/22(金)<br />○</li>
<li class="blu">7/23(土)<br />○</li>
<li class="pink">7/24(日)<br />○</li>
<li>7/25(月)<br />△</li>
<li>7/26(火)<br />○</li>
<li>7/27(水)<br />×</li>
<li>7/28(木)<br />○</li>
</ul>
<p>
<i class="fa fa-circle-thin" aria-hidden="true"></i> <i class="fa fa-ellipsis-h" aria-hidden="true"></i> 空きあり<br>
<i class="fa fa-commenting-o" aria-hidden="true"></i> <i class="fa fa-ellipsis-h" aria-hidden="true"></i> お申込の後運営会社より可否のご連絡<br>
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <i class="fa fa-ellipsis-h" aria-hidden="true"></i> 残り少し<br>
<i class="fa fa-times" aria-hidden="true"></i>  <i class="fa fa-ellipsis-h" aria-hidden="true"></i> 受付終了<br>
空欄 <i class="fa fa-ellipsis-h" aria-hidden="true"></i> 開催外<br>
</p>
</div><!-- /.listincalendar -->

</div><!-- /.reservation -->


</div><!-- /.tabAccordion -->

</div><!-- /.listin -->